const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const APP='https://maawaa.sa/assignment-response.html';

async function db(path:string,init:RequestInit={}){const url=Deno.env.get('SUPABASE_URL')||'',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const r=await fetch(url+path,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(`db_${r.status}:${JSON.stringify(b)?.slice(0,300)}`);return b}
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(v:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))))}
const money=(n:number)=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(n)+' ر.س';
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return hex(b)}

async function sendEmail(to:string,subject:string,html:string){const key=Deno.env.get('RESEND_API_KEY')||'';const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from:'تشغيل مأوى <info@maawaa.sa>',to:[to],reply_to:'info@maawaa.sa',subject,html})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`resend_${r.status}:${b?.message||''}`);return b.id}

async function details(id:string){const c=(await db(`/rest/v1/contracts?id=eq.${id}&select=id,contract_number,client_id,total_amount,service_type,property_location,shoot_date,notes,status`))?.[0];if(!c)throw new Error('contract_not_found');const u=(await db(`/rest/v1/clients?id=eq.${c.client_id}&select=full_name,email,phone_number`))?.[0];return {c,u}}

async function createOffer(contractId:string,dryRun:boolean){
  const existing=await db(`/rest/v1/assignment_offers?contract_id=eq.${contractId}&status=eq.pending&select=id`);if(existing?.length)return {skipped:'pending_offer_exists'};
  const ranked=await db('/rest/v1/rpc/recommend_photographers',{method:'POST',body:JSON.stringify({p_contract_id:contractId})});const pick=ranked?.[0];if(!pick)return {skipped:'no_available_photographer'};
  const {c,u}=await details(contractId);const recipient=(Deno.env.get('AUTOMATION_TEST_EMAIL')||'').trim();if(!recipient)throw new Error('test_email_missing');
  if(dryRun)return {dry_run:true,recipient,photographer:pick.employee_name,contract:c.contract_number,score:pick.score};
  const raw=token(),digest=await hash(raw),expires=new Date(Date.now()+12*3600000).toISOString();
  const inserted=await db('/rest/v1/assignment_offers',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({contract_id:contractId,employee_id:pick.employee_id,score:pick.score,response_token_hash:digest,sent_to:recipient,expires_at:expires})});
  const yes=`${APP}?token=${raw}&decision=accept`,no=`${APP}?token=${raw}&decision=reject`;
  const html=`<!doctype html><html lang="ar" dir="rtl"><body style="margin:0;background:#f2f0ed;font-family:Tahoma,Arial;color:#211e1c"><table width="100%"><tr><td align="center" style="padding:30px 12px"><table width="100%" style="max-width:620px;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="height:5px;background:#a4243b"></td></tr><tr><td style="padding:28px;background:#111;color:#fff"><b style="font-size:22px">طلب تصوير جديد</b><div style="color:#bbb;margin-top:7px">تجربة نظام التوزيع الذكي لمأوى</div></td></tr><tr><td style="padding:30px"><p>المصور المقترح: <b>${pick.employee_name}</b></p><h2 style="direction:ltr;text-align:right">${c.contract_number||'—'}</h2><p>العميل: ${u?.full_name||'—'}</p><p>الخدمة: ${c.service_type||'—'}</p><p>الموقع: ${c.property_location||'—'}</p><p>الموعد: ${c.shoot_date||'لم يحدد'}</p><p>قيمة الطلب: <b>${money(Number(c.total_amount||0))}</b></p><table><tr><td style="background:#167047;border-radius:8px"><a href="${yes}" style="display:block;padding:12px 25px;color:#fff;text-decoration:none;font-weight:bold">قبول الطلب</a></td><td width="10"></td><td style="background:#eee;border-radius:8px"><a href="${no}" style="display:block;padding:12px 25px;color:#7d2637;text-decoration:none;font-weight:bold">رفض الطلب</a></td></tr></table><p style="color:#888;font-size:12px">الرابط صالح 12 ساعة ويُقبل رد واحد فقط.</p></td></tr></table></td></tr></table></body></html>`;
  try{const emailId=await sendEmail(recipient,`طلب تصوير مقترح | ${c.contract_number||'مأوى'}`,html);await db('/rest/v1/automation_events',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({event_key:`offer:${inserted[0].id}`,contract_id:contractId,event_type:'assignment_offer',status:'sent',payload:{email_id:emailId,recipient,employee:pick.employee_name},processed_at:new Date().toISOString()})});return {ok:true,offer_id:inserted[0].id,recipient,photographer:pick.employee_name}}catch(e){await db(`/rest/v1/assignment_offers?id=eq.${inserted[0].id}`,{method:'PATCH',body:JSON.stringify({status:'cancelled'})});throw e}
}

async function respond(raw:string,decision:string){const digest=await hash(raw);const offer=(await db(`/rest/v1/assignment_offers?response_token_hash=eq.${digest}&select=id,contract_id,employee_id,status,expires_at,employees(name)`))?.[0];if(!offer)return json({error:'invalid_link'},404);if(offer.status!=='pending')return json({error:'already_answered',status:offer.status},409);if(new Date(offer.expires_at)<new Date()){await db(`/rest/v1/assignment_offers?id=eq.${offer.id}`,{method:'PATCH',body:JSON.stringify({status:'expired',responded_at:new Date().toISOString()})});return json({error:'expired'},410)};
  if(decision==='reject'){await db(`/rest/v1/assignment_offers?id=eq.${offer.id}&status=eq.pending`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'rejected',responded_at:new Date().toISOString()})});return json({ok:true,decision:'rejected',next_available:true})}
  if(decision!=='accept')return json({error:'invalid_decision'},400);
  await db('/rest/v1/assignments?on_conflict=contract_id,employee_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({contract_id:offer.contract_id,employee_id:offer.employee_id,role_in_job:'photographer',share_pct:70})});await db(`/rest/v1/assignment_offers?id=eq.${offer.id}&status=eq.pending`,{method:'PATCH',body:JSON.stringify({status:'accepted',responded_at:new Date().toISOString()})});await db('/rest/v1/contract_workflows?on_conflict=contract_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({contract_id:offer.contract_id,stage:'assigned',assigned_employee_id:offer.employee_id,updated_at:new Date().toISOString()})});return json({ok:true,decision:'accepted',photographer:offer.employees?.name||''})
}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const body=await req.json();if(body.action==='respond')return await respond(String(body.token||''),String(body.decision||''));const supplied=req.headers.get('x-automation-secret')||'';if(!supplied||supplied!==Deno.env.get('AUTOMATION_SECRET'))return json({error:'unauthorized'},401);const id=String(body.contract_id||'');if(!UUID.test(id))return json({error:'invalid_contract_id'},400);if(body.action==='offer')return json(await createOffer(id,Boolean(body.dry_run)));return json({error:'invalid_action'},400)}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'automation_failed'},500)}});
