const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'Content-Type':'application/json'}});
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const APP='https://maawaa.sa/schedule-change.html';
const esc=(v:unknown)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function hash(v:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))))}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return hex(b)}
async function signature(id:string){const secret=Deno.env.get('CONTRACT_APPROVAL_SECRET')||'';if(!secret)throw new Error('verify_secret_missing');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`verify:${id}`)))).slice(0,16)}
async function db(path:string,init:RequestInit={}){const base=Deno.env.get('SUPABASE_URL')||'',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const r=await fetch(base+path,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(`db_${r.status}:${JSON.stringify(b)?.slice(0,240)}`);return b}
async function email(to:string,subject:string,html:string){const key=Deno.env.get('RESEND_API_KEY')||'';const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from:'مأوى <info@maawaa.sa>',to:[to],reply_to:'info@maawaa.sa',subject,html})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`resend_${r.status}:${b?.message||''}`);return b.id}
const fmt=(v:string)=>new Intl.DateTimeFormat('ar-SA',{dateStyle:'full',timeStyle:'short',timeZone:'Asia/Riyadh'}).format(new Date(v));
function shell(title:string,body:string,badge='طلب تعديل موعد'){return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f1efec;font-family:Tahoma,Arial,sans-serif;color:#211e1c"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="100%" style="max-width:640px;background:#fbfaf7;border:1px solid #ded9d3;border-radius:18px;overflow:hidden"><tr><td style="height:5px;background:#a4243b"></td></tr><tr><td align="center" bgcolor="#090808" style="padding:22px;background-color:#090808!important"><img src="https://maawaa.sa/assets/logo2026/mawa-wide-white.svg" width="170" alt="مأوى" style="display:block;width:170px;max-width:100%;height:auto"></td></tr><tr><td style="padding:30px"><span style="display:inline-block;padding:7px 11px;border-radius:99px;background:#f7eff0;color:#a4243b;font-size:11px;font-weight:800">${badge}</span><h1 style="font-size:24px;margin:14px 0 16px">${title}</h1>${body}</td></tr><tr><td style="padding:18px;text-align:center;background:#ece8e3;color:#756e68;font-size:11px"><a href="mailto:info@maawaa.sa" style="color:inherit;text-decoration:none">info@maawaa.sa</a> · <a href="https://instagram.com/maawaasa" style="color:inherit;text-decoration:none">@maawaasa</a> · <a href="https://www.maawaa.sa" style="color:inherit;text-decoration:none">www.maawaa.sa</a></td></tr></table></td></tr></table></body></html>`}
async function contract(id:string){const c=(await db(`/rest/v1/contracts?id=eq.${id}&select=id,contract_number,client_id,shoot_date,property_location,status`))?.[0];if(!c)throw new Error('contract_not_found');const u=(await db(`/rest/v1/clients?id=eq.${c.client_id}&select=full_name,email`))?.[0];return {c,u}}
async function validate(id:string,sig:string){if(!UUID.test(id)||!sig||sig!==await signature(id))throw new Error('invalid_link');return contract(id)}

async function details(id:string,sig:string){const {c,u}=await validate(id,sig);const pending=(await db(`/rest/v1/schedule_change_requests?contract_id=eq.${id}&status=eq.pending&select=id,proposed_start,reason,requested_at`))?.[0]||null;return {ok:true,contract_number:c.contract_number,client_name:u?.full_name,current_date:c.shoot_date,location:c.property_location,pending,min_start:new Date(Date.now()+48*3600000).toISOString()}}

async function submit(id:string,sig:string,start:string,reason:string){const {c,u}=await validate(id,sig);const proposed=new Date(start);if(!Number.isFinite(proposed.getTime())||proposed.getTime()<Date.now()+47.5*3600000)throw new Error('date_too_soon');const exists=await db(`/rest/v1/schedule_change_requests?contract_id=eq.${id}&status=eq.pending&select=id`);if(exists?.length)return json({error:'pending_request_exists'},409);const raw=token(),digest=await hash(raw);const row=(await db('/rest/v1/schedule_change_requests',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({contract_id:id,current_shoot_date:c.shoot_date,proposed_start:proposed.toISOString(),reason:reason.slice(0,500),decision_token_hash:digest})}))?.[0];const approve=`${APP}?mode=decision&token=${raw}&decision=approve`,reject=`${APP}?mode=decision&token=${raw}&decision=reject`;const admin=(Deno.env.get('AUTOMATION_TEST_EMAIL')||'info@maawaa.sa').trim();const body=`<p style="color:#706963;line-height:1.9">طلب العميل <strong>${esc(u?.full_name)}</strong> تعديل موعد العقد <strong dir="ltr">${esc(c.contract_number)}</strong>.</p><table role="presentation" width="100%" style="background:#fff;border:1px solid #e5e0da;border-radius:12px"><tr><td style="padding:15px;color:#746d67">الموعد الحالي</td><td style="padding:15px;font-weight:800">${esc(c.shoot_date)}</td></tr><tr><td style="padding:15px;color:#746d67;border-top:1px solid #eee">الموعد المقترح</td><td style="padding:15px;font-weight:800;color:#a4243b;border-top:1px solid #eee">${esc(fmt(proposed.toISOString()))}</td></tr></table>${reason?`<p style="color:#706963">ملاحظة العميل: ${esc(reason)}</p>`:''}<table role="presentation" width="100%" style="margin-top:20px"><tr><td width="49%" align="center" style="background:#18794e;border-radius:9px"><a href="${approve}" style="display:block;padding:13px;color:#fff;text-decoration:none;font-weight:900">الموافقة على الموعد</a></td><td width="2%"></td><td width="49%" align="center" style="background:#c9364f;border-radius:9px"><a href="${reject}" style="display:block;padding:13px;color:#fff;text-decoration:none;font-weight:900">رفض الطلب</a></td></tr></table>`;await email(admin,`طلب تعديل موعد | ${c.contract_number}`,shell('موعد جديد بانتظار موافقة مأوى',body));return {ok:true,request_id:row.id}}

async function decide(raw:string,decision:string){const digest=await hash(raw);const q=(await db(`/rest/v1/schedule_change_requests?decision_token_hash=eq.${digest}&select=id,contract_id,status,proposed_start,reason`))?.[0];if(!q)throw new Error('invalid_link');if(q.status!=='pending')return json({error:'already_decided',status:q.status},409);if(!['approve','reject'].includes(decision))throw new Error('invalid_decision');const {c,u}=await contract(q.contract_id);const status=decision==='approve'?'approved':'rejected';await db(`/rest/v1/schedule_change_requests?id=eq.${q.id}&status=eq.pending`,{method:'PATCH',body:JSON.stringify({status,decided_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(decision==='approve'){const date=new Date(q.proposed_start).toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'});await db(`/rest/v1/contracts?id=eq.${q.contract_id}`,{method:'PATCH',body:JSON.stringify({shoot_date:date})});await db(`/rest/v1/schedule?contract_id=eq.${q.contract_id}`,{method:'PATCH',body:JSON.stringify({shoot_date:date,start_time:new Date(q.proposed_start).toLocaleTimeString('en-GB',{timeZone:'Asia/Riyadh',hour12:false}).slice(0,8)})});const people=await db(`/rest/v1/assignments?contract_id=eq.${q.contract_id}&select=employees(name,email)`);const body=`<p style="line-height:1.9;color:#706963">تمت الموافقة على تعديل موعد العقد <strong dir="ltr">${esc(c.contract_number)}</strong>.</p><div style="padding:18px;background:#e9f7ef;border:1px solid #cbe9d8;border-radius:12px;color:#18794e;font-weight:900">الموعد الجديد: ${esc(fmt(q.proposed_start))}</div>`;if(u?.email)await email(u.email,`تم تأكيد الموعد الجديد | ${c.contract_number}`,shell('تم تأكيد تعديل موعد الحجز',body,'تمت الموافقة'));for(const p of people||[]){if(p.employees?.email)await email(p.employees.email,`تم تعديل موعد الجلسة | ${c.contract_number}`,shell('تم تحديث موعد جلسة التصوير',body,'موعد محدّث'))}}else if(u?.email){await email(u.email,`تحديث طلب تعديل الموعد | ${c.contract_number}`,shell('تعذر اعتماد الموعد المقترح',`<p style="line-height:1.9;color:#706963">لم يُعتمد الموعد المقترح للعقد <strong dir="ltr">${esc(c.contract_number)}</strong>. يمكنك العودة إلى رسالة تأكيد الحجز واختيار موعد آخر.</p>`,'لم تتم الموافقة'))}return {ok:true,decision:status,contract_number:c.contract_number,proposed_start:q.proposed_start}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const b=await req.json();if(b.action==='details')return json(await details(String(b.contract_id||''),String(b.signature||'')));if(b.action==='submit')return await submit(String(b.contract_id||''),String(b.signature||''),String(b.proposed_start||''),String(b.reason||''));if(b.action==='decide')return await decide(String(b.token||''),String(b.decision||''));return json({error:'invalid_action'},400)}catch(e){console.error(e);const m=e instanceof Error?e.message:'schedule_change_failed';return json({error:m},m==='invalid_link'?403:400)}});
